spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/dadosapi
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring MVC e JSF
spring.mvc.servlet.path=/
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.xhtml

# JSF Configuration
joinfaces.jsf.project-stage=development
joinfaces.primefaces.theme=nova-light
joinfaces.primefaces.font-awesome=true